//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Parking
    {
        public int SlotId { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> DepartTime { get; set; }
        public Nullable<decimal> TotalFare { get; set; }
        public string RegistrationId { get; set; }
        public string VehicleType { get; set; }
        public string Floor { get; set; }
    }
}
